
version: '3'

services:
    front-end:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: front-end
        restart: always
        volumes:
            - ./:/app
            - /app/node_modules
        ports:
            - '3000:3000'
   